<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre 8 Partitionnement de la variation | Workshop 10: Advanced Multivariate Analyses in R</title>
  <meta name="description" content="Advanced Multivariate Analyses in R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre 8 Partitionnement de la variation | Workshop 10: Advanced Multivariate Analyses in R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://github.com/qcbsRworkshops/" />
  <meta property="og:image" content="https://github.com/qcbsRworkshops/assets/images/logo/csbq_logo_accueil.png" />
  <meta property="og:description" content="Advanced Multivariate Analyses in R" />
  <meta name="github-repo" content="qcbsRworkshops/workshop10" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre 8 Partitionnement de la variation | Workshop 10: Advanced Multivariate Analyses in R" />
  
  <meta name="twitter:description" content="Advanced Multivariate Analyses in R" />
  <meta name="twitter:image" content="https://github.com/qcbsRworkshops/assets/images/logo/csbq_logo_accueil.png" />

<meta name="author" content="Developed and maintained by the contributors of the QCBS R Workshop Series" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="assets/images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="rda-partielle.html"/>
<link rel="next" href="arbre-de-régression-multivarié.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/qcbs-style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="assets/images/csbq_logo_gray_accueil.png"></a></li>
<link rel="icon" type="image/png" href="assets/images/favicon.ico"/>

<li class="divider"></li>
<li class="part"><span><b>QCBS R Workshop Series</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#code-of-conduct"><i class="fa fa-check"></i><b>0.1</b> Code of conduct</a><ul>
<li class="chapter" data-level="0.1.1" data-path="index.html"><a href="index.html#expected-behaviour"><i class="fa fa-check"></i><b>0.1.1</b> Expected behaviour</a></li>
<li class="chapter" data-level="0.1.2" data-path="index.html"><a href="index.html#unacceptable-behaviour"><i class="fa fa-check"></i><b>0.1.2</b> Unacceptable behaviour</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i><b>0.2</b> Contributors</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#contributing"><i class="fa fa-check"></i><b>0.3</b> Contributing</a></li>
</ul></li>
<li class="part"><span><b>Analyses multivariées avancées dans <code>R</code></b></span></li>
<li class="chapter" data-level="1" data-path="objectifs-dapprentissage.html"><a href="objectifs-dapprentissage.html"><i class="fa fa-check"></i><b>1</b> Objectifs d’apprentissage</a></li>
<li class="chapter" data-level="2" data-path="préparez-vous-pour-cet-atelier.html"><a href="préparez-vous-pour-cet-atelier.html"><i class="fa fa-check"></i><b>2</b> Préparez-vous pour cet atelier</a></li>
<li class="chapter" data-level="3" data-path="why-advanced-multivariate-methods.html"><a href="why-advanced-multivariate-methods.html"><i class="fa fa-check"></i><b>3</b> Why “advanced multivariate methods”?</a></li>
<li class="chapter" data-level="4" data-path="exploration.html"><a href="exploration.html"><i class="fa fa-check"></i><b>4</b> Exploration les données</a><ul>
<li class="chapter" data-level="4.1" data-path="exploration.html"><a href="exploration.html#données-dabondances-despèces"><i class="fa fa-check"></i><b>4.1</b> Données d’abondances d’espèces</a></li>
<li class="chapter" data-level="4.2" data-path="exploration.html"><a href="exploration.html#données-environnementales"><i class="fa fa-check"></i><b>4.2</b> Données environnementales</a><ul>
<li class="chapter" data-level="4.2.1" data-path="exploration.html"><a href="exploration.html#colinéarité"><i class="fa fa-check"></i><b>4.2.1</b> Colinéarité</a></li>
<li class="chapter" data-level="4.2.2" data-path="exploration.html"><a href="exploration.html#standardisation-des-données"><i class="fa fa-check"></i><b>4.2.2</b> Standardisation des données</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Constrained ordinations</b></span></li>
<li class="chapter" data-level="5" data-path="que-sont-les-ordinations-contraintes.html"><a href="que-sont-les-ordinations-contraintes.html"><i class="fa fa-check"></i><b>5</b> Que sont les ordinations “contraintes” ?</a></li>
<li class="chapter" data-level="6" data-path="analyse-canonique-de-redondances.html"><a href="analyse-canonique-de-redondances.html"><i class="fa fa-check"></i><b>6</b> Analyse canonique de redondances</a><ul>
<li class="chapter" data-level="6.1" data-path="analyse-canonique-de-redondances.html"><a href="analyse-canonique-de-redondances.html#computation"><i class="fa fa-check"></i><b>6.1</b> Computation</a></li>
<li class="chapter" data-level="6.2" data-path="analyse-canonique-de-redondances.html"><a href="analyse-canonique-de-redondances.html#implémentation-dans-r"><i class="fa fa-check"></i><b>6.2</b> Implémentation dans R</a><ul>
<li class="chapter" data-level="6.2.1" data-path="analyse-canonique-de-redondances.html"><a href="analyse-canonique-de-redondances.html#sélection-de-variables"><i class="fa fa-check"></i><b>6.2.1</b> Sélection de variables</a></li>
<li class="chapter" data-level="6.2.2" data-path="analyse-canonique-de-redondances.html"><a href="analyse-canonique-de-redondances.html#tester-la-significativité"><i class="fa fa-check"></i><b>6.2.2</b> Tester la significativité</a></li>
<li class="chapter" data-level="6.2.3" data-path="analyse-canonique-de-redondances.html"><a href="analyse-canonique-de-redondances.html#représentation-graphique-des-rdas"><i class="fa fa-check"></i><b>6.2.3</b> Représentation graphique des RDAs</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="analyse-canonique-de-redondances.html"><a href="analyse-canonique-de-redondances.html#défi-1"><i class="fa fa-check"></i><b>6.3</b> Défi 1</a><ul>
<li class="chapter" data-level="6.3.1" data-path="analyse-canonique-de-redondances.html"><a href="analyse-canonique-de-redondances.html#défi-1-solution"><i class="fa fa-check"></i><b>6.3.1</b> Défi 1: Solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="rda-partielle.html"><a href="rda-partielle.html"><i class="fa fa-check"></i><b>7</b> RDA partielle</a><ul>
<li class="chapter" data-level="7.1" data-path="rda-partielle.html"><a href="rda-partielle.html#exemple-rda-partielle-sur-les-données-doubs"><i class="fa fa-check"></i><b>7.1</b> Exemple: RDA partielle sur les données Doubs</a><ul>
<li class="chapter" data-level="7.1.1" data-path="rda-partielle.html"><a href="rda-partielle.html#interprétation-de-la-sortie-dune-rda-partielle"><i class="fa fa-check"></i><b>7.1.1</b> Interprétation de la sortie d’une RDA partielle</a></li>
<li class="chapter" data-level="7.1.2" data-path="rda-partielle.html"><a href="rda-partielle.html#tester-la-significativité-1"><i class="fa fa-check"></i><b>7.1.2</b> Tester la significativité</a></li>
<li class="chapter" data-level="7.1.3" data-path="rda-partielle.html"><a href="rda-partielle.html#représentation-graphique"><i class="fa fa-check"></i><b>7.1.3</b> Représentation graphique</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="rda-partielle.html"><a href="rda-partielle.html#défi-2"><i class="fa fa-check"></i><b>7.2</b> Défi 2</a><ul>
<li class="chapter" data-level="7.2.1" data-path="rda-partielle.html"><a href="rda-partielle.html#défi-2-solution"><i class="fa fa-check"></i><b>7.2.1</b> Défi 2: Solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="partitionnement-de-la-variation.html"><a href="partitionnement-de-la-variation.html"><i class="fa fa-check"></i><b>8</b> Partitionnement de la variation</a><ul>
<li class="chapter" data-level="8.1" data-path="partitionnement-de-la-variation.html"><a href="partitionnement-de-la-variation.html#partitionnement-de-la-variation-dans-r"><i class="fa fa-check"></i><b>8.1</b> Partitionnement de la variation dans R</a></li>
<li class="chapter" data-level="8.2" data-path="partitionnement-de-la-variation.html"><a href="partitionnement-de-la-variation.html#tester-la-significativité-2"><i class="fa fa-check"></i><b>8.2</b> Tester la significativité</a></li>
<li class="chapter" data-level="8.3" data-path="partitionnement-de-la-variation.html"><a href="partitionnement-de-la-variation.html#défi-3"><i class="fa fa-check"></i><b>8.3</b> Défi 3</a><ul>
<li class="chapter" data-level="8.3.1" data-path="partitionnement-de-la-variation.html"><a href="partitionnement-de-la-variation.html#défi-3-solution"><i class="fa fa-check"></i><b>8.3.1</b> Défi 3: Solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html"><i class="fa fa-check"></i><b>9</b> Arbre de régression multivarié</a><ul>
<li class="chapter" data-level="9.1" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#computation-1"><i class="fa fa-check"></i><b>9.1</b> Computation</a><ul>
<li class="chapter" data-level="9.1.1" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#construction-de-larbre-partitionnement-des-données-sous-contrainte"><i class="fa fa-check"></i><b>9.1.1</b> Construction de l’arbre: Partitionnement des données sous contrainte</a></li>
<li class="chapter" data-level="9.1.2" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#sélection-de-larbre-validation-croisée-et-élagage-de-larbre"><i class="fa fa-check"></i><b>9.1.2</b> Sélection de l’arbre: Validation croisée et élagage de l’arbre</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#mrt-dans-r"><i class="fa fa-check"></i><b>9.2</b> MRT dans R</a><ul>
<li class="chapter" data-level="9.2.1" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#processus-de-sélection"><i class="fa fa-check"></i><b>9.2.1</b> Processus de sélection</a></li>
<li class="chapter" data-level="9.2.2" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#interprétation-des-résultats"><i class="fa fa-check"></i><b>9.2.2</b> Interprétation des résultats</a></li>
<li class="chapter" data-level="9.2.3" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#indicator-species"><i class="fa fa-check"></i><b>9.2.3</b> Indicator species</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#défi-4"><i class="fa fa-check"></i><b>9.3</b> Défi 4</a><ul>
<li class="chapter" data-level="9.3.1" data-path="arbre-de-régression-multivarié.html"><a href="arbre-de-régression-multivarié.html#challenge-4-solution"><i class="fa fa-check"></i><b>9.3.1</b> Challenge 4: Solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="analyse-discriminante-linéaire.html"><a href="analyse-discriminante-linéaire.html"><i class="fa fa-check"></i><b>10</b> Analyse discriminante linéaire</a><ul>
<li class="chapter" data-level="10.1" data-path="analyse-discriminante-linéaire.html"><a href="analyse-discriminante-linéaire.html#lda-dans-r-rivière-doubs"><i class="fa fa-check"></i><b>10.1</b> LDA dans R: Rivière Doubs</a><ul>
<li class="chapter" data-level="10.1.1" data-path="analyse-discriminante-linéaire.html"><a href="analyse-discriminante-linéaire.html#créer-des-groupes-a-priori"><i class="fa fa-check"></i><b>10.1.1</b> Créer des groupes <em>a priori</em></a></li>
<li class="chapter" data-level="10.1.2" data-path="analyse-discriminante-linéaire.html"><a href="analyse-discriminante-linéaire.html#lda-dans-r"><i class="fa fa-check"></i><b>10.1.2</b> LDA dans R</a></li>
<li class="chapter" data-level="10.1.3" data-path="analyse-discriminante-linéaire.html"><a href="analyse-discriminante-linéaire.html#exactitude-du-groupement"><i class="fa fa-check"></i><b>10.1.3</b> Exactitude du groupement</a></li>
<li class="chapter" data-level="10.1.4" data-path="analyse-discriminante-linéaire.html"><a href="analyse-discriminante-linéaire.html#prédictions"><i class="fa fa-check"></i><b>10.1.4</b> Prédictions</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="analyse-discriminante-linéaire.html"><a href="analyse-discriminante-linéaire.html#défi-5"><i class="fa fa-check"></i><b>10.2</b> Défi 5</a></li>
</ul></li>
<li class="part"><span><b>Considérations finales</b></span></li>
<li class="chapter" data-level="11" data-path="résumé.html"><a href="résumé.html"><i class="fa fa-check"></i><b>11</b> Résumé</a></li>
<li class="chapter" data-level="12" data-path="ressources-additionelles.html"><a href="ressources-additionelles.html"><i class="fa fa-check"></i><b>12</b> Ressources additionelles</a></li>
<li class="chapter" data-level="13" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>13</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/qcbsRworkshops" target="blank">QCBS R Workshop Series</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Workshop 10: Advanced Multivariate Analyses in <code>R</code></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!------------------------ Hero Image Container --------------------------> 

<head>
  <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=10.0,initial-scale=1.0">
  <script src="https://kit.fontawesome.com/6a26f47516.js"></script>
  <script src="assets/qcbs-hideOutput.js"></script>
  <link href="assets/qcbs-style.css" rel="stylesheet">
</head>



<div class="hero-image-container"> 
  <img class= "hero-image" src="assets/images/jean-philippe-delberghe-75xPHEQBmvA-unsplash_hero_image.jpg">
</div>
<div id="partitionnement-de-la-variation" class="section level1">
<h1><span class="header-section-number">Chapitre 8</span> Partitionnement de la variation</h1>
<p>Le partitionnement de la variation est un type d’analyse qui combine à
la fois la RDA et la RDA partielle pour diviser la variation d’une
matrice de variable réponse en deux, trois ou quatre jeux de données
explicatives. Par exemple, on pourrait partitionner la variation dans une matrice de communauté en fonctiond e variables abiotiques et biotiques, ou de variables locales et à large
échelle.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-52"></span>
<img src="images/VarPart_Matrices.png" alt="La structure d'un partitionnement de la variation." width="60%" />
<p class="caption">
Figure 8.1: La structure d’un partitionnement de la variation.
</p>
</div>
<p>Le résultat d’un partitionnement de la variation est
généralement représenté par un diagramme de Venn sur lequel sont annotés
les pourcentages de variance expliquée par chacun des jeux de données
explicatives. Dans le cas où on partionnerait la variation entre deux matrices explicatives, le résultat pourrait être représenté comme suit:</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-53"></span>
<img src="images/VarPart.png" alt="Représentation des résultats d'un partitionnement de la variation." width="80%" />
<p class="caption">
Figure 8.2: Représentation des résultats d’un partitionnement de la variation.
</p>
</div>
<p>Ici, les fraction représentent:</p>
<ul>
<li>La fraction <span class="math inline">\([a + b + c]\)</span> est la variance expliquée par <em><span class="math inline">\(X1\)</span> </em>et* <span class="math inline">\(X2\)</span> ensemble, calculée à partir d’une RDA de <span class="math inline">\(Y\)</span> par <span class="math inline">\(X1 + X2\)</span>.<br />
</li>
<li>La fraction <span class="math inline">\([d]\)</span> est la variance inexpliquée par <em><span class="math inline">\(X1\)</span> </em>et* <span class="math inline">\(X2\)</span> ensemble, obtenue à partir de la même RDA que ci-dessus.<br />
</li>
<li>La fraction <span class="math inline">\([a]\)</span> est la variance expliquée par <span class="math inline">\(X1\)</span> <em>seulement</em>, calculée en faisant une RDA partielle de <span class="math inline">\(Y\)</span> par <span class="math inline">\(X1 | X2\)</span> (en contrôlant pour <span class="math inline">\(X2\)</span>).<br />
</li>
<li>La fraction <span class="math inline">\([c]\)</span> est la variance expliquée par <span class="math inline">\(X2\)</span> <em>seulement</em>, calculée en faisant une RDA partielle de <span class="math inline">\(Y\)</span> par <span class="math inline">\(X2 | X1\)</span> (en contrôlant pour <span class="math inline">\(X1\)</span>).<br />
</li>
<li>La fraction <span class="math inline">\([b]\)</span> est calculée par soustraction, c’est-à-dire <span class="math inline">\(b = [a + b] + [b + c] - [a + b + c].\)</span> Comme <span class="math inline">\([b]\)</span> n’est pas le résultat d’une RDA, il est impossible de tester sa significativité. Elle peut également être négative, ce qui indique que la matrice de réponse est mieux expliquée par la combinaison de <span class="math inline">\(X1\)</span> et <span class="math inline">\(X2\)</span> que par l’une ou l’autre des matrices prise individuellement.</li>
</ul>
<div id="partitionnement-de-la-variation-dans-r" class="section level2">
<h2><span class="header-section-number">8.1</span> Partitionnement de la variation dans R</h2>
<p>Pour démontrer comment le partitionnement des variations fonctionne dans <code>R</code>, nous allons partitionner la variation de la composition des espèces de poissons entre les variables chimiques et topographiques. La fonction <code>varpart()</code> de <code>vegan</code> nous facilite la tâche.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="partitionnement-de-la-variation.html#cb73-1"></a><span class="co"># Partitionner la variation de la composition des espèces de</span></span>
<span id="cb73-2"><a href="partitionnement-de-la-variation.html#cb73-2"></a><span class="co"># poissons</span></span>
<span id="cb73-3"><a href="partitionnement-de-la-variation.html#cb73-3"></a>spe.part.all &lt;-<span class="st"> </span><span class="kw">varpart</span>(spe.hel, env.chem, env.topo)</span>
<span id="cb73-4"><a href="partitionnement-de-la-variation.html#cb73-4"></a>spe.part.all<span class="op">$</span>part  <span class="co"># access results!</span></span></code></pre></div>
<pre><code>## No. of explanatory tables: 2 
## Total variation (SS): 14.07 
##             Variance: 0.50251 
## No. of observations: 29 
## 
## Partition table:
##                      Df R.squared Adj.R.squared Testable
## [a+b] = X1            7   0.60579       0.47439     TRUE
## [b+c] = X2            3   0.41526       0.34509     TRUE
## [a+b+c] = X1+X2      10   0.73414       0.58644     TRUE
## Individual fractions                                    
## [a] = X1|X2           7                 0.24135     TRUE
## [b]                   0                 0.23304    FALSE
## [c] = X2|X1           3                 0.11205     TRUE
## [d] = Residuals                         0.41356    FALSE
## ---
## Use function &#39;rda&#39; to test significance of fractions of interest</code></pre>
<p>On peut ensuite visualiser les résultats avec la fonction <code>plot()</code>.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="partitionnement-de-la-variation.html#cb75-1"></a><span class="co"># Visualiser les résultats avec un diagramme Venn</span></span>
<span id="cb75-2"><a href="partitionnement-de-la-variation.html#cb75-2"></a><span class="kw">plot</span>(spe.part.all,</span>
<span id="cb75-3"><a href="partitionnement-de-la-variation.html#cb75-3"></a>     <span class="dt">Xnames =</span> <span class="kw">c</span>(<span class="st">&quot;Chem&quot;</span>, <span class="st">&quot;Topo&quot;</span>), <span class="co"># noms des matrices explicatives</span></span>
<span id="cb75-4"><a href="partitionnement-de-la-variation.html#cb75-4"></a>     <span class="dt">bg =</span> <span class="kw">c</span>(<span class="st">&quot;seagreen3&quot;</span>, <span class="st">&quot;mediumpurple&quot;</span>), <span class="dt">alpha =</span> <span class="dv">80</span>,</span>
<span id="cb75-5"><a href="partitionnement-de-la-variation.html#cb75-5"></a>     <span class="dt">digits =</span> <span class="dv">2</span>,</span>
<span id="cb75-6"><a href="partitionnement-de-la-variation.html#cb75-6"></a>     <span class="dt">cex =</span> <span class="fl">1.5</span>)</span></code></pre></div>
<p><img src="book-fr_files/figure-html/unnamed-chunk-55-1.png" width="576" /></p>
<p>Les variables chimiques expliquent <strong>24.1%</strong> de la variation de la composition des espèces de poissons, les variables topographiques expliquent <strong>11.2%</strong> de la variation de la composition des espèces de poissons, et ces deux groupes de variables <strong>conjointement</strong> expliquent <strong>23.3%</strong> de la variation de la composition des espèces de poissons.</p>
<div class="explanation">
<p>Soyez prudent lorsque vous rapportez les résultats du partitionnement de la variation ! La fraction partagée [b] ne représente pas un effet <em>d’interaction</em> des deux matrices explicatives. Considérez-la comme un <em>chevauchement</em> entre <span class="math inline">\(X1\)</span> et <span class="math inline">\(X2\)</span>. Elle représente la fraction <em>partagée</em> de la variation expliquée lorsque les deux sont incluses dans le modèle, c’est-à-dire la partie de la variation qui ne peut être attribuée à <span class="math inline">\(X1\)</span> ou <span class="math inline">\(X2\)</span> séparément. En d’autres termes, le partitionnement de la variation ne peut pas démêler les effets de la chimie et de la topographie pour 23.3% de la variation de la composition de la communauté de poissons.</p>
</div>
</div>
<div id="tester-la-significativité-2" class="section level2">
<h2><span class="header-section-number">8.2</span> Tester la significativité</h2>
<p>La sortie de la fonction <code>varpart()</code> rapporte le <span class="math inline">\(R^2\)</span> ajusté pour chaque fraction, mais vous remarquerez que le tableau n’inclut aucun test de signification statistique. Cependant, la colonne <code>Testable</code> identifie les fractions qui peuvent être testées pour leur signification en utilisant la fonction <code>anova.cca()</code>, tout comme nous l’avons fait avec le RDA !</p>
<p><strong>X1 [a+b]: Chimie sans tenir compte de topographie</strong></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="partitionnement-de-la-variation.html#cb76-1"></a><span class="co"># [a+b] Chimie sans tenir compte de topographie</span></span>
<span id="cb76-2"><a href="partitionnement-de-la-variation.html#cb76-2"></a><span class="kw">anova.cca</span>(<span class="kw">rda</span>(spe.hel, env.chem))</span></code></pre></div>
<pre><code>## Permutation test for rda under reduced model
## Permutation: free
## Number of permutations: 999
## 
## Model: rda(X = spe.hel, Y = env.chem)
##          Df Variance      F Pr(&gt;F)    
## Model     7  0.30442 4.6102  0.001 ***
## Residual 21  0.19809                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>X2 [b+c] Topographie sans tenir compte de chimie</strong></p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="partitionnement-de-la-variation.html#cb78-1"></a><span class="co"># [b+c] Topographie sans tenir compte de chimie</span></span>
<span id="cb78-2"><a href="partitionnement-de-la-variation.html#cb78-2"></a><span class="kw">anova.cca</span>(<span class="kw">rda</span>(spe.hel, env.topo))</span></code></pre></div>
<pre><code>## Permutation test for rda under reduced model
## Permutation: free
## Number of permutations: 999
## 
## Model: rda(X = spe.hel, Y = env.topo)
##          Df Variance     F Pr(&gt;F)    
## Model     3  0.20867 5.918  0.001 ***
## Residual 25  0.29384                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>X1 | X2 [a] Chimie seulement (ajusté pour tenir compte de topographie)</strong></p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="partitionnement-de-la-variation.html#cb80-1"></a><span class="co"># [a] Chimie seulement</span></span>
<span id="cb80-2"><a href="partitionnement-de-la-variation.html#cb80-2"></a><span class="kw">anova.cca</span>(<span class="kw">rda</span>(spe.hel, env.chem, env.topo))</span></code></pre></div>
<pre><code>## Permutation test for rda under reduced model
## Permutation: free
## Number of permutations: 999
## 
## Model: rda(X = spe.hel, Y = env.chem, Z = env.topo)
##          Df Variance      F Pr(&gt;F)    
## Model     7  0.16024 3.0842  0.001 ***
## Residual 18  0.13360                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<blockquote>
<p>C’est une RDA partielle!</p>
</blockquote>
<p><strong>X2 | X1 [c] Topographie (ajusté pour tenir compte de chimie)</strong></p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="partitionnement-de-la-variation.html#cb82-1"></a><span class="co"># [c] Topographie seulement</span></span>
<span id="cb82-2"><a href="partitionnement-de-la-variation.html#cb82-2"></a><span class="kw">anova.cca</span>(<span class="kw">rda</span>(spe.hel, env.chem, env.topo))</span></code></pre></div>
<pre><code>## Permutation test for rda under reduced model
## Permutation: free
## Number of permutations: 999
## 
## Model: rda(X = spe.hel, Y = env.chem, Z = env.topo)
##          Df Variance      F Pr(&gt;F)    
## Model     7  0.16024 3.0842  0.001 ***
## Residual 18  0.13360                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Toutes les fractions testables dans le partitionnement de la variation sont statistiquement significatives!</p>
</div>
<div id="défi-3" class="section level2">
<h2><span class="header-section-number">8.3</span> Défi 3</h2>
<p>Partitionnez la variation de l’abondance des espèces de mites entres des variables de substrat (<code>SubsDens</code>, <code>WatrCont</code>) et des variables spatiales significatives.</p>
<ul>
<li>Quelle est la proportion de variance expliquée par le substrat? par l’espace?<br />
</li>
<li>Quelles sont les fractions significatives?<br />
</li>
<li>Diagramme Venn des résultats!</li>
</ul>
<p>Chargez les variables spatiales:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="partitionnement-de-la-variation.html#cb84-1"></a><span class="kw">data</span>(<span class="st">&quot;mite.pcnm&quot;</span>)</span></code></pre></div>
<p>Rappel de fonctions utiles:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="partitionnement-de-la-variation.html#cb85-1"></a><span class="kw">ordiR2step</span>()</span>
<span id="cb85-2"><a href="partitionnement-de-la-variation.html#cb85-2"></a><span class="kw">varpart</span>()</span>
<span id="cb85-3"><a href="partitionnement-de-la-variation.html#cb85-3"></a><span class="kw">anova.cca</span>(<span class="kw">rda</span>())</span>
<span id="cb85-4"><a href="partitionnement-de-la-variation.html#cb85-4"></a><span class="kw">plot</span>()</span></code></pre></div>
<div id="défi-3-solution" class="section level3">
<h3><span class="header-section-number">8.3.1</span> Défi 3: Solution</h3>
<p><strong>Étape 1:</strong> Sélection de variables spatiales significatives.</p>
<p>Il y a <em>beaucoup</em> de variables spatiales dans ce jeu de données (22 !). Nous devrions sélectionner les plus importantes, pour éviter de surcharger le modèle.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="partitionnement-de-la-variation.html#cb86-1"></a><span class="co"># Modèle RDA avec tous les variables spatiales</span></span>
<span id="cb86-2"><a href="partitionnement-de-la-variation.html#cb86-2"></a>full.spat &lt;-<span class="st"> </span><span class="kw">rda</span>(mite.spe.hel <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> mite.pcnm)</span>
<span id="cb86-3"><a href="partitionnement-de-la-variation.html#cb86-3"></a></span>
<span id="cb86-4"><a href="partitionnement-de-la-variation.html#cb86-4"></a><span class="co"># Sélection progressive des variables spatiales</span></span>
<span id="cb86-5"><a href="partitionnement-de-la-variation.html#cb86-5"></a>spat.sel &lt;-<span class="st"> </span><span class="kw">ordiR2step</span>(<span class="kw">rda</span>(mite.spe.hel <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> mite.pcnm), </span>
<span id="cb86-6"><a href="partitionnement-de-la-variation.html#cb86-6"></a>    <span class="dt">scope =</span> <span class="kw">formula</span>(full.spat), <span class="dt">R2scope =</span> <span class="kw">RsquareAdj</span>(full.spat)<span class="op">$</span>adj.r.squared, </span>
<span id="cb86-7"><a href="partitionnement-de-la-variation.html#cb86-7"></a>    <span class="dt">direction =</span> <span class="st">&quot;forward&quot;</span>, <span class="dt">trace =</span> <span class="ot">FALSE</span>)</span>
<span id="cb86-8"><a href="partitionnement-de-la-variation.html#cb86-8"></a>spat.sel<span class="op">$</span>call</span></code></pre></div>
<pre><code>## rda(formula = mite.spe.hel ~ V2 + V3 + V8 + V1 + V6 + V4 + V9 + 
##     V16 + V7 + V20, data = mite.pcnm)</code></pre>
<p><strong>Étape 2:</strong> Créer sous-groupes de variables explicatives.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="partitionnement-de-la-variation.html#cb88-1"></a><span class="co"># Variables de substrat</span></span>
<span id="cb88-2"><a href="partitionnement-de-la-variation.html#cb88-2"></a>mite.subs &lt;-<span class="st"> </span><span class="kw">subset</span>(mite.env, <span class="dt">select =</span> <span class="kw">c</span>(SubsDens, WatrCont))</span>
<span id="cb88-3"><a href="partitionnement-de-la-variation.html#cb88-3"></a></span>
<span id="cb88-4"><a href="partitionnement-de-la-variation.html#cb88-4"></a><span class="co"># Variables spatiales significatives</span></span>
<span id="cb88-5"><a href="partitionnement-de-la-variation.html#cb88-5"></a>mite.spat &lt;-<span class="st"> </span><span class="kw">subset</span>(mite.pcnm, <span class="dt">select =</span> <span class="kw">names</span>(spat.sel<span class="op">$</span>terminfo<span class="op">$</span>ordered))</span>
<span id="cb88-6"><a href="partitionnement-de-la-variation.html#cb88-6"></a><span class="co"># pour rapidement accèder aux variables sélectionnées</span></span></code></pre></div>
<p><strong>Étape 3:</strong> Partitionnement de la variation dans la matrice d’abondances.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="partitionnement-de-la-variation.html#cb89-1"></a>mite.part &lt;-<span class="st"> </span><span class="kw">varpart</span>(mite.spe.hel, mite.subs, mite.spat)</span>
<span id="cb89-2"><a href="partitionnement-de-la-variation.html#cb89-2"></a>mite.part<span class="op">$</span>part<span class="op">$</span>indfract  <span class="co"># extraire résultats</span></span></code></pre></div>
<pre><code>##                 Df R.squared Adj.R.squared Testable
## [a] = X1|X2      2        NA    0.05901929     TRUE
## [b]              0        NA    0.24765221    FALSE
## [c] = X2|X1     10        NA    0.19415929     TRUE
## [d] = Residuals NA        NA    0.49916921    FALSE</code></pre>
<ul>
<li>Quelle est la proportion de variance expliquée par le substrat? <strong>5.9%</strong></li>
<li>Quelle est la proportion de variance expliquée par l’espace? <strong>19.4%</strong></li>
</ul>
<p><strong>Étape 4:</strong> Quelles sont les fractions significatives?</p>
<p><strong>[a]: Substrat seulement</strong></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="partitionnement-de-la-variation.html#cb91-1"></a><span class="kw">anova.cca</span>(<span class="kw">rda</span>(mite.spe.hel, mite.subs, mite.spat))</span></code></pre></div>
<pre><code>...
## Model: rda(X = mite.spe.hel, Y = mite.subs, Z = mite.spat)
##          Df Variance      F Pr(&gt;F)    
## Model     2 0.025602 4.4879  0.001 ***
## Residual 57 0.162583                  
...</code></pre>
<p><strong>[c]: Espace seulement</strong></p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="partitionnement-de-la-variation.html#cb93-1"></a><span class="kw">anova.cca</span>(<span class="kw">rda</span>(mite.spe.hel, mite.spat, mite.subs))</span></code></pre></div>
<pre><code>...
## Model: rda(X = mite.spe.hel, Y = mite.spat, Z = mite.subs)
##          Df Variance      F Pr(&gt;F)    
## Model    10  0.10286 3.6061  0.001 ***
## Residual 57  0.16258                  
...</code></pre>
<p><strong>Étape 5:</strong> Visualiser les résultats avec un diagramme Venn.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="partitionnement-de-la-variation.html#cb95-1"></a><span class="kw">plot</span>(mite.part,</span>
<span id="cb95-2"><a href="partitionnement-de-la-variation.html#cb95-2"></a>     <span class="dt">digits =</span> <span class="dv">2</span>,</span>
<span id="cb95-3"><a href="partitionnement-de-la-variation.html#cb95-3"></a>     <span class="dt">Xnames =</span> <span class="kw">c</span>(<span class="st">&quot;Subs&quot;</span>, <span class="st">&quot;Space&quot;</span>), <span class="co"># titre des fractions</span></span>
<span id="cb95-4"><a href="partitionnement-de-la-variation.html#cb95-4"></a>     <span class="dt">cex =</span> <span class="fl">1.5</span>,</span>
<span id="cb95-5"><a href="partitionnement-de-la-variation.html#cb95-5"></a>     <span class="dt">bg =</span> <span class="kw">c</span>(<span class="st">&quot;seagreen3&quot;</span>, <span class="st">&quot;mediumpurple&quot;</span>), <span class="co"># ajoutez des couleurs!</span></span>
<span id="cb95-6"><a href="partitionnement-de-la-variation.html#cb95-6"></a>     <span class="dt">alpha =</span> <span class="dv">80</span>)</span></code></pre></div>
<p><img src="book-fr_files/figure-html/unnamed-chunk-70-1.png" width="576" /></p>
<p><strong>Alors, quels sont les effets de substrat et de l’espace sur les abondances d’espèces de mites?</strong></p>
<p><strong>Indice:</strong> Pourquoi on trouve un effet si important de l’espace?</p>
<p>L’espace explique la plupart de la variation dans la communauté: elle explique <strong>19.4% (p = 0.001)</strong> de la variation seule, et <strong>24.8%</strong> est expliqué <em>conjointement</em> par l’espace et le substrat. Le susbtrat n’explique que <strong>~6% (p = 0.001)</strong> de la variation entre sites sans l’effet de l’espace. Notez également que la moitié de la variation n’est pas expliquée par les variables que nous avons incluses dans le modèle (regardez les résidus !), le modèle pourrait donc être amélioré.</p>
<blockquote>
<p>Cet effet élevé de l’espace <em>pourrait</em> être un signe qu’un processus écologique spatial est important ici (comme la dispersion, par exemple). *Cependant, il pourrait aussi nous indiquer que nous manquons une variable environnementale importante dans notre modèle, qui varie elle-même dans l’espace!</p>
</blockquote>

</div>
</div>
</div>
<hr>
<center> 
  <div class="footer">
      All the content of the workshop series is under a <a href="https://creativecommons.org/licenses/by-nc/2.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
  </div>
</center>
            </section>

          </div>
        </div>
      </div>
<a href="rda-partielle.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="arbre-de-régression-multivarié.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
